ModelPool Serialization
Klebert-Engineering/simfil pull request #32
Opened 2023-05-09 21:23 UTC by josephbirkner

2023-05-21 20:54 UTC, johannes-wolf requested changes

2023-05-21 20:54 UTC, johannes-wolf commented on include/simfil/model/arena.h
> +    using sizeType = SizeType;
Nitpick: `using SizeType = SizeType_;`? Lower case s looks strange for a typedef.

2023-05-21 20:54 UTC, johannes-wolf commented on include/simfil/model/arena.h
> +        auto operator[] (size_t const& i) const { return begin_.arena_.at(begin_.array_index_, i); }
Maybe use `decltype(auto)` here?

2023-05-21 20:54 UTC, johannes-wolf commented on test/arena.cpp
> +        arena.push_back(array1, 44);
What is tested here?

2023-05-21 20:54 UTC, johannes-wolf commented on include/simfil/model/fields.h
> +    std::unordered_map<FieldId, std::string> stringForId_;
Are the values of `FieldId` continous? Is so, we could maybe use a vector for `FieldId->String` lookup. Everytime I had meassured `map` vs `unordered_map` the latter performed worse.

2023-05-22 12:17 UTC, josephbirkner commented on test/arena.cpp
> +        arena.push_back(array1, 44);
Ooops

2023-05-22 14:42 UTC, johannes-wolf commented on include/simfil/model/fields.h
> +    std::unordered_map<FieldId, std::string> stringForId_;
The example is very bad because `std::hash` for ints is way cheaper than for strings.

2023-05-24 14:19 UTC, josephbirkner commented on include/simfil/model/arena.h
> +    using sizeType = SizeType;
I agree

2023-05-25 16:08 UTC, josephbirkner commented on include/simfil/model/nodes.h
Oh, good catch.

2023-05-31 17:56 UTC, johannes-wolf approved these changes
LGTM.

2023-05-31 17:59 UTC, merged