Update & Improve Readme
Klebert-Engineering/simfil pull request #41
Opened 2023-05-27 15:13 UTC by johannes-wolf

2023-05-30 10:44 UTC, josephbirkner commented
Nice 🎇 Some more ideas:

* Graphical Architecture Overview (Relationships between `Expr`, `Environment`, `Fields`, `Model`, `Nodes`)
* API integration example with CMake/C++
* C++ Model extension example?

2023-06-04 16:01 UTC, johannes-wolf commented
Would like to merge this and add additions as separate PRs.

2023-06-09 13:06 UTC, MisterGC requested changes

2023-06-09 13:06 UTC, MisterGC commented on README.md
>  For details about the language see the [Language Guide](simfil-language.md).
Which kind of sources of inspiration have been used to come up with the language, what are the key aspects covered - as we list specific examples we should also briefly cover the language (and then still reference the language specification)

2023-06-09 13:06 UTC, MisterGC commented on README.md
> +```sh
Write something about the platforms/toolchains that have been confirmed/can be used - are there specific requirements/dependencies?

2023-06-09 13:06 UTC, MisterGC commented on README.md
> +## Using the Repl
Don't assume that all users know 'Read-Eval-Print-Loop' but call the section something like 'Try it yourself with the simfil command line tool'  or something. Describe what the tool is about.

2023-06-09 13:06 UTC, MisterGC commented on README.md
> +## Query Language
Add a 'Repo Structure' section and briefly describe about how the repo is organized.

2023-06-12 07:02 UTC, MisterGC approved these changes

2023-06-12 12:04 UTC, merged

2023-06-12 12:04 UTC, johannes-wolf commented
Will do additional changes as follow up PRs.