Add ModelPool::transcode
Klebert-Engineering/simfil pull request #75
Opened 2024-03-13 15:08 UTC by josephbirkner

Motivation: Allow two features which are encoded with different field dicts to be evaluated under one OverlayLaynode, which combines the two feature nodes which come from different models.

2024-03-13 17:20 UTC, josephbirkner commented on src/model/fields.cpp
> +Fields::Fields(const Fields& other) :
Note: This copy ctor impl cannot be defaulted because of the shared_lock member.

2024-03-13 17:53 UTC, johannes-wolf requested changes

2024-03-14 08:45 UTC, josephbirkner commented on src/model/model.cpp
> +void ModelPool::transcode(std::shared_ptr<simfil::Fields> const& newDict)
Good point. As we have `fieldNames()`, I went with "setFieldNames".

2024-03-14 08:46 UTC, josephbirkner commented on src/model/model.cpp
> +    impl_->fieldNames_ = std::make_shared<Fields>(*impl_->fieldNames_);
I got rid of the method.

2024-03-14 18:36 UTC, johannes-wolf approved these changes
LGTM :guitar:

2024-03-14 22:20 UTC, merged